Repository iamgoodbytes/2imd-webtechadvanced-labs, pull requests merged in 2020-03, with the labels that each got.

#57 Added .md with link to portfolio
  Yanis_De_Maesschalck.md
Labels: updatesrequired

#61 added lab3 and mongodb university
  timothy_koenig.md
Labels: bug, updatesrequired

#63 changed readme.md
  Lisa_Drse.md
Labels: updatesrequired

#66 lab2 klaar
  Jens_Wouters.md
Labels: updatesrequired

#69 Finished lab 2
  Bram_Theunis.md
Labels: updatesrequired

#77 Added link to lab 3 to .md file
  Ward_Vandevoort.md
Labels: question

#80 Lab3
  marlena_broniewicz.md
Labels: updatesrequired

#76 Added lab 2
  Rani_Verelst.md
Labels: updatesrequired

#101 Added link to Lab3 ES6
  Tommy_denHollander.md
Labels: updatesrequired

#90 Add link to Lab3 Notes app
  Luna_Olbrechts.md
Labels: updatesrequired

#105 added lab 5
  timothy_koenig.md
Labels: updatesrequired

#117 Lab 4 added
  vincent_van_de_sompel.md
Labels: updatesrequired

#120 Added lab 4
  Jasper_Peeters.md
Labels: updatesrequired

#98 bug fixed week3 + MongoDB
  Miguel_Lammens.md
Labels: updatesrequired
