Repository iamgoodbytes/2imd-webtechadvanced-labs, pull requests merged in 2022-03, with the labels that each got.

#39 feat: Add Lab3 link to markdown file
  Bram_Colleman.md
Labels: 🐞 need bugfixes

#36 docx: Added Lab 2 to jef_fasseur.md
  jef_fasseur.md
Labels: ℹ️ need more info

#41 feat: update with lab3
  Ellen_deVeth.md
Labels: 💪🏻more work required

#42 feat: add lab 3 and JS-feature
  Marianne_Neuts.md
Labels: 💪🏻more work required

#43 feat: update with lab 3 + recent js feature
  Alejandro_De_Wolf.md
Labels: 💪🏻more work required

#49 docs(lab3): Add lab 3 to portfolio
  Nicolas_van_der_Straten_Ponthoz.md
Labels: 💪🏻more work required

#50 feat: update with lab4
  Ellen_deVeth.md
Labels: 🐞 need bugfixes

#57 docs(lab4): Add lab 4 to portfolio
  Nicolas_van_der_Straten_Ponthoz.md
Labels: 🐞 need bugfixes

#48 update: updated Marie_Serroyen.md with lab3 link
  Marie_Serroyen.md
Labels: 💪🏻more work required

#55 feat: add lab 3 link to markdown file
  liena_paeps.md
Labels: 💪🏻more work required

#61 update: finished Lab4
  Liam_Peeters.md
Labels: 💪🏻more work required

#60 update on jef_fasseur.md: Added lab 3 for approval
  jef_fasseur.md
Labels: 💪🏻more work required

#71 feat: add lab 4 link to markdown file
  liena_paeps.md
Labels: 🐞 need bugfixes
